In [42]:
using LinearAlgebra

# Multi-Diemensional Arrays
An array is a collection of objects stored din a multi-dimensional grid. An array may contain objects of type Any. In Julia, all arguments to functions are *passed by sharing* (by pointers) or also known as *passed by reference*. In a way, there are a lot of overlap for functionality for Multi-dimension arrays between Julia and Python's Numpy.

## Instantiating Arrays

In [6]:
A = [1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [10]:
# Can add different types of variables in an array
B = [1 2 3; 4 5 "what"]

2×3 Array{Any,2}:
 1  2  3      
 4  5   "what"

## zeroes (np.zeros)
Similar to np.zeros. Create an Array with elmeent type T of all zeros with size specified by dims
* 1 - data type (optional)
* 2 - ndims...: number of dimensions is a splat

In [15]:
# data type: Int64 and number of dimensions is (2,3)
zeros(Int64, 2, 3)

2×3 Array{Int64,2}:
 0  0  0
 0  0  0

In [16]:
# nmber of dimensions is (3,3,3)
zeros(3,3,3)

3×3×3 Array{Float64,3}:
[:, :, 1] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 2] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

[:, :, 3] =
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

## fill (np.fill)
Similar to np.fill. Create an array filled with the value *x* with the dimensions *dims*
* 1 - value
* 2 - dimensions (tuple): dimensions of the returned array

In [17]:
fill(3.0, (5,5))

5×5 Array{Float64,2}:
 3.0  3.0  3.0  3.0  3.0
 3.0  3.0  3.0  3.0  3.0
 3.0  3.0  3.0  3.0  3.0
 3.0  3.0  3.0  3.0  3.0
 3.0  3.0  3.0  3.0  3.0

## collect (np.arange)
Similar to np.arange. Just like np.arange, specify start, end, and step
* 1 - start
* 2 - step
* 3 - end

In [3]:
collect(1:3:16)

6-element Array{Int64,1}:
  1
  4
  7
 10
 13
 16

## range (np.linsapce)
Similar to np.linspace, split an array starting from *start* to *end* *length* times
* 1 - start (Number): start Number
* 2 - stop (Number): end Number
* 3 - length (Int64): Number of times to split the list

In [1]:
range(0.1,stop=1.1,length=5) # returns a UnitRange of (start:step:end)

0.1:0.25:1.1

In [24]:
range(0.1, stop=1.1, length=5) |> collect

5-element Array{Float64,1}:
 0.1 
 0.35
 0.6 
 0.85
 1.1 

# rand (np.random.random)
Similar to np.random.random. Will return an array of x random integers 1-D.
* 1 - Data Type (String)
* 2 - dimensions...: Specify dimensions of returned random array

In [23]:
# Floats range from 0 to 1
rand(Float64, 3, 3, 5)

3×3×5 Array{Float64,3}:
[:, :, 1] =
 0.344561  0.803465   0.839299
 0.375167  0.33846    0.845633
 0.219437  0.0895327  0.851019

[:, :, 2] =
 0.200277  0.91564   0.995686
 0.669491  0.526893  0.50558 
 0.706238  0.687182  0.466273

[:, :, 3] =
 0.57666    0.00434535  0.106806
 0.964271   0.657348    0.814901
 0.0472938  0.369176    0.835135

[:, :, 4] =
 0.458092   0.43466   0.903759
 0.0128981  0.69987   0.203006
 0.912396   0.977112  0.368626

[:, :, 5] =
 0.506323  0.938837  0.741266 
 0.274991  0.601488  0.146314 
 0.824404  0.656362  0.0364332

In [18]:
rand(Int, 5)

5-element Array{Int64,1}:
  8538685834459681839
  2270779642252033072
 -1881186325226556446
  3280226743413924543
 -1556662722217289953

In [31]:
rand(Float64, (5,))

5-element Array{Float64,1}:
 0.3337949880350146 
 0.18212135493799253
 0.9708707650243735 
 0.539067826986056  
 0.8335640791087267 

# randn (np.random.random.normal)
similar to np.random.random.nomral. Generate a normally-distributed random number of tyep T with mean 0 and standard deviation 1. Can only return Float64 types.
* 1 - Dimensions... (or tuple): Dimensions of the returning array

In [35]:
randn((3, 3))

3×3 Array{Float64,2}:
 -0.099837  -0.00602161   0.280635
  0.155443   1.76637     -1.87221 
  0.360204  -0.29127     -0.610494

In [36]:
randn((5, 5))

5×5 Array{Float64,2}:
  1.08376     0.146268  -0.0805756   0.213667   1.37211  
  0.721964    0.701999  -0.118345    0.600663   0.0228073
 -0.0365176   0.112624   0.460405    2.3804     1.32359  
 -0.122327   -0.177919  -0.879353   -0.177092   1.57367  
 -1.66092     1.31069   -0.0114995   0.399705  -1.08336  

# I | one (np.eye)
Similar to np.eye. Create an identity matrix, by adding I to a multi-dimensional array (n x n) will add identity matrix. Pass an array to 'one' to form an identity matrix from that.

In [44]:
one(rand(Float64, (3,3)))

3×3 Array{Float64,2}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [43]:
rand(Float64, (3,3)) + I

3×3 Array{Float64,2}:
 1.40412   0.174599  0.990297
 0.673908  1.16219   0.993254
 0.669172  0.63092   1.82308 

## Diagonal (np.diag)
Get the diagonal of the given matrix. Return an array with the same dimensions but with just the diagonal as values.
* 1 - 2-D array.

In [45]:
A = [1 2 3; 4 5 6; 7 8 9]

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [46]:
Diagonal(A)

3×3 Diagonal{Int64,Array{Int64,1}}:
 1  ⋅  ⋅
 ⋅  5  ⋅
 ⋅  ⋅  9

# diag (np.diag)
Get the diagonal of the given matrix. Return an array in a 1-D array.
* 1 - array

In [47]:
diag(A)

3-element Array{Int64,1}:
 1
 5
 9

# diagm (np.diag)
Similar to np.diag. Construct a square matrix from Pairs of diagonals and vectors. Vector kv.second will be placed on the kv.first diagonal.

In [63]:
diagm(0 => [1, 2, 3])

3×3 Array{Int64,2}:
 1  0  0
 0  2  0
 0  0  3

In [64]:
diagm(1 => [4,5])

3×3 Array{Int64,2}:
 0  4  0
 0  0  5
 0  0  0

In [65]:
diagm(1 => [4,5,6])

4×4 Array{Int64,2}:
 0  4  0  0
 0  0  5  0
 0  0  0  6
 0  0  0  0

## Pair
A Pair is simliar to a tuple / dictionary. So, Pair(x, y) == x => y. "foo" => 7. You can access the first element with .first and the second element with .second.

In [55]:
x = Pair("st", 8)

"st" => 8

In [62]:
print(x.first, " . ", x.second)

st . 8

In [59]:
typeof(3 => "st")

Pair{Int64,String}

In [56]:
y = Dict(Pair("st", 8), Pair("lol", 12))
y

Dict{String,Int64} with 2 entries:
  "st"  => 8
  "lol" => 12

In [57]:
y["st"]

8

## size (np.array.shape)
Similar to np.array.shape. Returns a tuple containing the dimensions of A.
* 1 - array

In [74]:
A = [1 2 3; 4 5 6; 7 8 9]
size(A)

(3, 3)

## length (np.array.size)
Similar to size. Returns the number of elements in **A**
* 1 - Array

In [75]:
length(A)

9

## ndims (np.array.ndim)
Similar to ndim. Returns the number of dimensions in **A**.
* 1 - Array

In [79]:
ndims(A)

2

## Array Indexing
There are several ways to index an array, the first is in place with no functions, the other is with functions. Utilizing functions is the easiest way to index through an array.

In [2]:
A = [1 2 3; 4 5 6; 7 8 9]
A

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

In [50]:
# The equivalent of list comprehension
# second for loop is like an inner for loop while the first for loop
# is like an outer for loop
A = [c + r for c in 0:3:6, r in 1:1:3]
A

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

# getindex
Gets the index of the specified array at the indices passed along.
* 1 - Array
* 2 - indices...

In [109]:
getindex(A, 1, 2) == A[1,2]

true

In [111]:
getindex(A, 1, 1)

1

In [51]:
# can't use end for getindex
getindex(A, end)

LoadError: syntax: unexpected "end"

In [52]:
A[2, 3] # Prints 6, row 2 column 3 (1 - based index)

6

In [53]:
A[1, 1] # Prints 1, row 1 column 1

1

In [54]:
# use keyword end in place of '-1' index
A[1, end]

3

In [55]:
A[end, end]

9

In [56]:
# getting rows
A[end, :]

3-element Array{Int64,1}:
 7
 8
 9

In [57]:
# getting columns
A[:, 2]

3-element Array{Int64,1}:
 2
 5
 8

In [58]:
# gets all rows up to the third row
A[1:2, :]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [60]:
A[end:-1:1, end:-1:1]

3×3 Array{Int64,2}:
 9  8  7
 6  5  4
 3  2  1

In [65]:
A[1:1:2, :]

2×3 Array{Int64,2}:
 1  2  3
 4  5  6

In [75]:
A[1:1:2, 2:1:2]

2×1 Array{Int64,2}:
 2
 5

# reshape (np.reshape)
Reshapes the array into the tuple specified
* 1 - array (A)
* 2 - tuple - a size 2 tuple that specifies what the array will be transformed into

In [80]:
# creates a 6 x 5 array
A = [r + c for r in 0:5:25, c in 1:1:5]

6×5 Array{Int64,2}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15
 16  17  18  19  20
 21  22  23  24  25
 26  27  28  29  30

In [81]:
reshape(A, (5, 6))

5×6 Array{Int64,2}:
  1  26  22  18  14  10
  6   2  27  23  19  15
 11   7   3  28  24  20
 16  12   8   4  29  25
 21  17  13   9   5  30

In [83]:
reshape(A, (15, 2))

15×2 Array{Int64,2}:
  1  18
  6  23
 11  28
 16   4
 21   9
 26  14
  2  19
  7  24
 12  29
 17   5
 22  10
 27  15
  3  20
  8  25
 13  30

# cat (np.concatenate)
Concatenates the passed arrays
* 1 - Arrays (splat): Arrays to be concatenated
* 2 - dims (1 or 2): dims is the dimension that the first array will be concatenated onto. 1 is the x-axis,and 2 is the y-axis.


In [84]:
A

6×5 Array{Int64,2}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15
 16  17  18  19  20
 21  22  23  24  25
 26  27  28  29  30

In [86]:
B = [r + c for r in 1:1:5, c in 1:1:5]
B

5×5 Array{Int64,2}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [95]:
c = [r + c for r in 1:1:6, c in 1:1:6]
c

6×6 Array{Int64,2}:
 2  3  4   5   6   7
 3  4  5   6   7   8
 4  5  6   7   8   9
 5  6  7   8   9  10
 6  7  8   9  10  11
 7  8  9  10  11  12

In [94]:
cat(A, B, dims=1)

11×5 Array{Int64,2}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15
 16  17  18  19  20
 21  22  23  24  25
 26  27  28  29  30
  2   3   4   5   6
  3   4   5   6   7
  4   5   6   7   8
  5   6   7   8   9
  6   7   8   9  10

In [96]:
cat(A, c, dims=2)

6×11 Array{Int64,2}:
  1   2   3   4   5  2  3  4   5   6   7
  6   7   8   9  10  3  4  5   6   7   8
 11  12  13  14  15  4  5  6   7   8   9
 16  17  18  19  20  5  6  7   8   9  10
 21  22  23  24  25  6  7  8   9  10  11
 26  27  28  29  30  7  8  9  10  11  12

# vcat cat(A..., dims=1) (np.vstack)
Will vertically concatenate (stack) the arrays into one, given that the first dimensions match (x-axis)
* 1 - A... (arrays to be concatenated)

In [98]:
vcat(A, B)

11×5 Array{Int64,2}:
  1   2   3   4   5
  6   7   8   9  10
 11  12  13  14  15
 16  17  18  19  20
 21  22  23  24  25
 26  27  28  29  30
  2   3   4   5   6
  3   4   5   6   7
  4   5   6   7   8
  5   6   7   8   9
  6   7   8   9  10

# hcat cat(A..., dims=2) (np.hstack)
Will horizontally concatenate (append) the arrays into one, given that the first dimensions match (y-axis)

In [99]:
hcat(A, c)

6×11 Array{Int64,2}:
  1   2   3   4   5  2  3  4   5   6   7
  6   7   8   9  10  3  4  5   6   7   8
 11  12  13  14  15  4  5  6   7   8   9
 16  17  18  19  20  5  6  7   8   9  10
 21  22  23  24  25  6  7  8   9  10  11
 26  27  28  29  30  7  8  9  10  11  12

# Vectorized Operations

In [2]:
A = [r + c for r in 1:1:3, c in 1:1:2]
A

3×2 Array{Int64,2}:
 2  3
 3  4
 4  5

In [3]:
B = [r - c for r in 1:1:3, c in 1:1:2]
B

3×2 Array{Int64,2}:
 0  -1
 1   0
 2   1

# broadcast
Broadcasts an operation and the value onto an array. 
* 1 - operation (symbol)
* 2 - value_1 (any numerical value)
* 3 - value_2 (any numerical value)

In [4]:
broadcast(+, 1, A)

3×2 Array{Int64,2}:
 3  4
 4  5
 5  6

In [5]:
broadcast(/, A, B)

3×2 Array{Float64,2}:
 Inf     -3.0
   3.0  Inf  
   2.0    5.0

# mapslices
Transform the given dimensions of array **A** using function **f**.

In [6]:
A

3×2 Array{Int64,2}:
 2  3
 3  4
 4  5

In [7]:
# calculate sum along the x-axis
mapslices(sum, A, dims=1)

1×2 Array{Int64,2}:
 9  12

In [8]:
# calculate sum along the y-axis
mapslices(sum, A, dims=2)

3×1 Array{Int64,2}:
 5
 7
 9

In [10]:
function max(arr)
    val = 0
    for i in arr
        if i > val
            val = i
        end
    end
    return val
end
mapslices(max, A, dims=2)

3×1 Array{Int64,2}:
 3
 4
 5

In [23]:
# closest thing to creating boolean arrays
function less_than_3(arr)
    lst = []
    for ele in arr
        if ele < 3
            push!(lst, true)
        else
            push!(lst, false)
        end
    end
    return lst
end

mapslices(less_than_3, A, dims=1)

3×2 Array{Any,2}:
  true  false
 false  false
 false  false

ErrorException: function broadcast does not accept keyword arguments

## eltype
Returns the type of the elements contained in **A**
* 1 - Array

In [8]:
eltype(A)

Int64

In [9]:
eltype(B)

Any