# What is Julia?
Julia is a functional language that alllows for the performance and R, yet utilizes the syntax of Python.

## Basics of Programming Languages
* There are several different rules that programming languages follow.
### Type Checking
* There are two types of type-checking
#### Static
* you have to specify the variable's type prior to using
#### Dynamic
* you don't have to specify

# Datatypes and Operators

* **Int64** - 64 bit integers
* **Float64** - 64 bit floats
* **Complex{Int64}** - 64 bit complex (complex data type that is a data type made of primitive (base) data types)
* **Rational{Int64}** - 64 bit rational number (a number that can be expressed as the quotient or fraction p/q of two integers)

In [1]:
typeof(3)

Int64

In [2]:
typeof(3.2)

Float64

In [4]:
# im is imaginary number
typeof(im)

Complex{Bool}

In [6]:
typeof(2 + im)

Complex{Int64}

In [8]:
# // is integer division -> rational number
typeof(2//3)

Rational{Int64}

# Basic arithmetic operations

In [9]:
1 + 1

2

In [10]:
8 - 1

7

In [11]:
10 * 2

20

In [12]:
# Dividing integers always results in a Float64 variable
35/5

7.0

In [13]:
# 10 = dividend 2 = divisor 5 = quotient
10/2

5.0

In [15]:
# Truncated division
div(5,2)

2

In [18]:
div(10,6)

1

In [19]:
# Division in reverse order (divisor / dividend)
5 \ 35

7.0

In [22]:
# raised to the power of
3 ^ 4

81

In [23]:
# modulous operation
10 % 3

1

In [25]:
# parantheses for enforcing precedence
(1 + 3) * 2

8

# Bitwise Operations

In [27]:
# bitwise not
# ..0010
# ~...0010-> ...1101
# ~ ...1101 -> ...0010 + 1 -> ...0011 -> 3
~2

-3

In [28]:
# bitwise and
#  011 -> 3
#& 101 -> 5
#  001
3 & 5

1

In [29]:
# bitwise or
#  010
#| 100
#  110
2 | 4

6

In [31]:
# if different -> 1, if same -> 0
# bitwise xor
#  010
#^ 100
#  110
xor(2, 4)

6

In [34]:
# logical shift right (will append a 0 regardless of Most Significant
# bit)
#   010
#>>>001
2 >>> 1

1

In [35]:
# arithmetic shift right (will append a value depending on Most 
# Significant Bit)
#  010
#>>010
2 >> 1

1

In [36]:
2 << 1

4

## bitstring
Converts an integer to bits
* 1 - integer (int): integer that will be converted to bits

In [37]:
# integer bit
bitstring(12345)

"0000000000000000000000000000000000000000000000000011000000111001"

In [39]:
# IEEE-754 floating point integers
bitstring(12345.0)

"0100000011001000000111001000000000000000000000000000000000000000"

# Boolean Comparisons

In [40]:
!true

false

In [41]:
1 ==1 

true

In [42]:
1 != 1

false

In [43]:
1 < 10

true

In [44]:
2 <= 2

true

In [45]:
1 < 2 < 3

true

In [46]:
1 < 5 < 2

false

# Strings and Characters

In [47]:
# Creating a string
"This is a string."

"This is a string."

In [48]:
typeof("This is a string")

String

In [49]:
# Different thatn characters in Python
'a'

'a': ASCII/Unicode U+0061 (category Ll: Letter, lowercase)

In [51]:
# Will throw an error if you add additional characters enclosed in 
# single characters
'ab'

LoadError: syntax: invalid character literal

In [54]:
# Only if a string contains ASCII characters, they can be safely 
# indeexed
ascii("This is a string")[1]

'T': ASCII/Unicode U+0054 (category Lu: Letter, uppercase)

In [56]:
# $ can be used for string interpolation. You can put any Julia 
# expression inside the parentheses
"2 + 2 = $(2 + 2)"

"2 + 2 = 4"

In [58]:
# Format strings with stdlib Printf
using Printf
@printf "%d is less than %f\n" 4.5 5.3

5 is less than 5.300000


In [59]:
# printing strings
println("what")

what


In [62]:
# b is greater than a in ascii values
"aood" > "bye"

false

In [63]:
"good" == "good"

true

In [65]:
"1 + 2 = 3" == "1 + 2 = $(1 + 2)"

true

# Variables and Collections

In [66]:
# Declaring variables
someVar = 5

5

In [67]:
someVar

5

In [68]:
# Instead of try and except, use try and catch.
try
    someOtherVar
catch e
    println(e)
end

UndefVarError(:someOtherVar)


In [70]:
# error of creating a variable
someOtherVar

UndefVarError: UndefVarError: someOtherVar not defined

In [71]:
# Variables HAVE TO start with a letter or underscore
# After that, you can use anything, even exclamation points
SomeOtherVar123! = 6

6

In [73]:
# You can also use certain unicode characters (even pi)
2 * π

6.283185307179586

## Naming Conventions in Julia
* Work separation can be indicated by ('_'), however underscores are discouraged
* Name of Types begin with a capital letter and word separation with CamelCase
* Function / Macros names are in lower case without underscores
    * Functions that modify their inputs have names that end in !. Functions are called mutating functions or in-place functions

## Instantiating Arrays
Arrays can hold any type of elements. Can hold a mixture of types or a single type.

In [79]:
# Julia is indexed by integers 1 through n
# 0-element array
a = Int64[]
a

0-element Array{Int64,1}

In [82]:
# 1-dimensional array literals with comma (or semi-colon) separated 
# values
b = [4, 5, 6]

3-element Array{Int64,1}:
 4
 5
 6

In [83]:
b = [4;5;6]

3-element Array{Int64,1}:
 4
 5
 6

In [85]:
# first value is 1-base index
b[1]

4

In [87]:
# end is a keyword, end is the last element in a list
b[end]

6

In [88]:
# 2-dimensional arrays use space-separated values and semicolon
# - separated rows
matrix = [1 2; 3 4]

2×2 Array{Int64,2}:
 1  2
 3  4

In [89]:
# Arrays of a particular type
b = Int8[4, 5, 6]

3-element Array{Int8,1}:
 4
 5
 6

## push!
Appends to the end of the list
* 1 - target array (list): The target array to mutate
* 2 - value (some value): Value to append to the array

In [90]:
# appending elements to the list
# REMINDER: ! at the end of a function will mutate it's arguments
push!(a, 1)

1-element Array{Int64,1}:
 1

In [91]:
push!(a, 2)

2-element Array{Int64,1}:
 1
 2

In [92]:
push!(a, 4)

3-element Array{Int64,1}:
 1
 2
 4

In [93]:
push!(a, 3)

4-element Array{Int64,1}:
 1
 2
 4
 3

## append!
Appends one list to another list
* 1 - target (list): base list
* 2 - target (list): list appended to base list

In [94]:
append!(a, b)

7-element Array{Int64,1}:
 1
 2
 4
 3
 4
 5
 6

In [95]:
# pop removes the last element in the list
pop!(b)

6

In [96]:
b

2-element Array{Int8,1}:
 4
 5

In [98]:
push!(b, 6)

4-element Array{Int8,1}:
 4
 5
 6
 6

## popfirst!
pop the first element in the list
* 1 - list: target list

In [100]:
popfirst!(a)

1

In [101]:
a

6-element Array{Int64,1}:
 2
 4
 3
 4
 5
 6

## pushfirst!
Pushes an element to the beginning of the list
* 1 - list: target list
* 2 - value: value to be pushed to the list

In [102]:
pushfirst!(a, 8)

7-element Array{Int64,1}:
 8
 2
 4
 3
 4
 5
 6

In [103]:
arr = [5,4,6]

3-element Array{Int64,1}:
 5
 4
 6

## sort(!)
Without exclamation mark: returns the sorted array but doesn't mutate the argument array
With exclamation mark: mutates the argument array
* 1 - list: target list

In [113]:
sort(arr)

3-element Array{Int64,1}:
 4
 5
 6

In [114]:
arr

3-element Array{Int64,1}:
 5
 4
 6

In [115]:
sort!(arr)

3-element Array{Int64,1}:
 4
 5
 6

In [116]:
arr

3-element Array{Int64,1}:
 4
 5
 6

In [119]:
try
    # Can't access index 0 (Julia is index based 1 programming language)
    a[0]
    # Capped at end+1 index for arrays
    a[end+1]
catch e
    println(e)
end

BoundsError([2, 3, 4, 4, 5, 6, 8], (0,))


In [120]:
a = [1:5;]

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [122]:
# creating a unit range will let the user iterate through a range of
# numbers (kind of like an iterable of integers)
a2 = [1:5]

1-element Array{UnitRange{Int64},1}:
 1:5

In [127]:
a2[1]

1:5

In [128]:
a2[1][2]

2

In [129]:
a[1:3]

3-element Array{Int64,1}:
 1
 2
 3

In [130]:
a[2:end]

4-element Array{Int64,1}:
 2
 3
 4
 5

In [131]:
arr=[3,4,5]

3-element Array{Int64,1}:
 3
 4
 5

## splice!
Only mutation function exists<br/>
Removes an lement in an array at a given index
* 1- list (array): Target array
* 2- index (integer): Index to remove the element

In [134]:
splice!(arr, 2)

4

In [135]:
b = [1,2,3]

3-element Array{Int64,1}:
 1
 2
 3

In [136]:
a

5-element Array{Int64,1}:
 1
 2
 3
 4
 5

In [137]:
append!(a, b)

8-element Array{Int64,1}:
 1
 2
 3
 4
 5
 1
 2
 3

## in
Checks for the existance of an elmeent
* 1 - value: The element to check for
* 2 - list (array): Array to compare with

In [138]:
in(1, a)

true

## length
Returns the length of the array as an integer
* 1 - array

In [139]:
length(a)

8

In [142]:
a = ['a', "wha", 3]

3-element Array{Any,1}:
  'a'  
  "wha"
 3     

## Instantiating a tuple
Tuples are immutable, so once instantiated, can't rewrite elements in the tuple

In [140]:
tup = (1,2,3)

(1, 2, 3)

In [141]:
typeof(tup)

Tuple{Int64,Int64,Int64}

In [143]:
tup[1]

1

In [145]:
# Trying to set index
try
    tup[1] = 3
catch e
    println(e)
end

MethodError(setindex!, ((1, 2, 3), 3, 1), 0x00000000000061ea)


In [146]:
# the same functions that work for the array will probably work for 
# tuples as well
length(tup)

3

In [147]:
tup[1:2]

(1, 2)

In [148]:
in(2, tup)

true

In [149]:
# Unpacking values from the tuple into variables
a, b, c=(1,2,3)
a

1

In [150]:
b

2

In [151]:
c

3

In [152]:
# Instantiating multiple varialbe doesn't require tuples
d, e, f = 4, 5, 6
d

4

In [153]:
e

5

In [154]:
f

6

In [156]:
# same syntax to instantiate a tuple with one 
(1,)

(1,)

In [157]:
(1) == 1

true

In [158]:
(1, ) == 1

false

## Instantiating Dictionaries

In [155]:
# DICTIONARIES YESSSSS
emptyDict = Dict()

Dict{Any,Any} with 0 entries

In [161]:
# Dictionary won't be sorted or instantiated in order they were 
# instantiated (just like python)
filledDict = Dict("one" => 1, "two"=>2, "three"=>3)

Dict{String,Int64} with 3 entries:
  "two"   => 2
  "one"   => 1
  "three" => 3

In [160]:
filledDict["one"]

1

## keys
Returns the keys of the given dictionary
* 1 - Dict: Target Dictionary

In [163]:
#Getting all of the keys
keys(filledDict)

Base.KeySet for a Dict{String,Int64} with 3 entries. Keys:
  "two"
  "one"
  "three"

## values
Returns the values of the given dictionary (in order of the keys returned from the keys() function
* 1 - Dict: Target dictionary

In [165]:
values(filledDict)

Base.ValueIterator for a Dict{String,Int64} with 3 entries. Values:
  2
  1
  3

In [166]:
in(("one" => 1), filledDict)

true

In [167]:
in(("two" => 3), filledDict)

false

## haskey
Returns true or false if the dictionary includes the given key
* 1 - dict
* 2 - element: Key value to compare within the dictionary

In [168]:
haskey(filledDict, "one")

true

In [169]:
haskey(filledDict, 1)

false

In [170]:
try
    filledDict["four"]
catch e
    println(e)
end

KeyError("four")


## get
Avoids the throwing a keyerror in the case that the key passed does not have an existing value
* 1 - dictionary
* 2 - key: key value
* 3 - ret_val: in case the key value throws a KeyError, return this value

In [171]:
get(filledDict, "one", 4)

1

In [172]:
get(filledDict, "four", 9)

9

## Instantiating Sets
Sets are unordered and only include unique values<br/>A lot of operations from array carry over to Sets

In [174]:
emptySet =Set()

Set(Any[])

In [175]:
filledSet = Set([1,2,3,3,4,5,5,5,5])

Set([4, 2, 3, 5, 1])

In [176]:
push!(filledSet, 5)

Set([4, 2, 3, 5, 1])

In [177]:
push!(filledSet, 6)

Set([4, 2, 3, 5, 6, 1])

In [178]:
in(2, filledSet)

true

In [179]:
in(10, filledSet)

false

## intersect
Determine if there are elements that exist in both sets
* 1 - set1
* 2 - set2

In [185]:
otherSet = Set([4,5,3,2,13])

Set([4, 13, 2, 3, 5])

In [186]:
intersect(otherSet, filledSet)

Set([4, 2, 3, 5])

## Union
Return all unique elements as a collection of both sets
* 1 - set1
* 2 - set2

In [187]:
union(otherSet, filledSet)

Set([4, 13, 2, 3, 5, 6, 1])

## setdiff
Return the difference of the two sets
* 1 - set
* 2 - set

In [189]:
setdiff(Set([1,2,3,4]), Set([2,3,5]))

Set([4, 1])

# Control Flow

In [190]:
someVar = 5

5

In [192]:
# control flow
if someVar > 10
    println("someVar is totally bigger than 10.")
elseif someVar < 10
    println("someVar is smaller than 10.")
else
    println("someVar is indeed 10.")
end

someVar is smaller than 10.


In [194]:
# for loops can iterate through iterables
# Use $(variable) for string interpolation
for animal = ["dog", "cat", "mouse"]
    println("$animal is a mammal")
end

dog is a mammal
cat is a mammal
mouse is a mammal


In [197]:
# can also iterate through dictionaires
# however is not in order
# the key value pair equal to the variable pair, then unpack those 
# values by setting them equal to from, to
for pair in Dict("dog" => "mammal", "cat" => "mammal", "mouse"=>"mammal")
    from, to = pair
    println("$from is $to")
end

mouse is mammal
cat is mammal
dog is mammal


In [200]:
# instead of creating a new variable called pair, can set the two 
# variables equal to (k, v) <- need to encolse in parentheses, need
# to use tuples
for (k, v) in Dict("cat" => "mammal", "truck" => "vehcile", "sandwich" => "food")
    println("$k is a $v")
end

truck is a vehcile
cat is a mammal
sandwich is a food


In [206]:
# the let keyword is similar to the with keyword, will create a
# variable in the body of the code following the keyword, but once
# outside of the body, the variable no longer exists
let x = 0
    while x < 4
        println(x)
        x += 1
    end
    println("what $x")
end
# here, x no longer exists
println("$x")

0
1
2
3
what 4


UndefVarError: UndefVarError: x not defined

In [207]:
try
    error("help")
catch e
    println("caught it $e")
end

caught it ErrorException("help")


# Functions

In [209]:
# defining a function is just like python, instead of def, use 
# function
# instantiating a function
function add(x, y)
    println("x is $x and y is $y")
    x + y
end

add (generic function with 1 method)

In [210]:
add(3, 5)

x is 3 and y is 5


8

In [211]:
# compact assignment of functions (like lambdas)
f_add(x, y) = x + y

f_add (generic function with 1 method)

In [212]:
f_add(3,5)

8

In [213]:
fn(x, y) = x + y, x - y

fn (generic function with 1 method)

In [214]:
fn(3, 5)

(8, -2)

In [218]:
# how to specify multiple arguments
# '...' is called a splace, 
function varargs(args...)
    return args
end

varargs (generic function with 1 method)

In [219]:
varargs(1,2,3, "wha")

(1, 2, 3, "wha")

In [223]:
# splatting will 'splat' an Array or Tuple's contents into the argument
# list
add([4,5]...)

x is 4 and y is 5


9

In [224]:
add((3,4)...)

x is 3 and y is 4


7

In [231]:
# Positional arguments are arguments, when passed, are assumed that 
# the argument correspondes to the placeholder argument that is
# defined within the function
# e.x.: add(5,3)
# Keyword arguments are arguments that are explicitly declared within
# the function header e.x.: add(x=5, y=3)

In [225]:
# you can also define optional positional arguments
function defaults(a, b, add([4,5]...)x=5, y=6)
    return "$a $b and $x $y"
end

defaults (generic function with 3 methods)

In [226]:
defaults('h', 'g')

"h g and 5 6"

In [227]:
defaults('h', 'g', 'j')

"h g and j 6"

In [228]:
defaults('h', 'g', 'j', 'k')

"h g and j k"

In [230]:
# passing in one or no arguments to a function that has two 
# mandatory arguments will throw an error (MethodError)
try 
    defaults('h')
    defaults()
catch e
    println(e)
end

MethodError(defaults, ('h',), 0x00000000000061f3)


In [246]:
# keyword arguments vs. positional arguments
function keyword_args(k1=4, name2="hello")
    return Dict("k1"=>k1, "name2"=>name2)
end

keyword_args (generic function with 3 methods)

In [247]:
keyword_args(k1="mine")

Dict{String,String} with 2 entries:
  "name2" => "hello"
  "k1"    => "mine"

In [248]:
keyword_args(name2="ness")

Dict{String,Any} with 2 entries:
  "name2" => "ness"
  "k1"    => 4

In [249]:
keyword_args()

Dict{String,Any} with 2 entries:
  "name2" => "hello"
  "k1"    => 4

In [250]:
# keyword arguments vs. positional arguments
# by convention, it's good to declare the beginning of the argument
# statement with a semicolon
function keyword_args(;k1=4, name2="hello")
    return Dict("k1"=>k1, "name2"=>name2)
end

keyword_args (generic function with 3 methods)

In [243]:
keyword_args(name2="ness")

Dict{String,Any} with 2 entries:
  "name2" => "ness"
  "k1"    => 4

In [244]:
keyword_args(k1="mine")

Dict{String,String} with 2 entries:
  "name2" => "hello"
  "k1"    => "mine"

In [245]:
keyword_args()

Dict{String,Any} with 2 entries:
  "name2" => "hello"
  "k1"    => 4

In [251]:
function all_the_args(normalArg, optionalPositionalArg=2; keywordArg="foo")
    println("normal arg: $normalArg")
    println("optional arg: $optionalPositionalArg")
    println("keyword arg: $keywordArg")
end

all_the_args (generic function with 2 methods)

In [252]:
all_the_args(1,3,keywordArg=4)

normal arg: 1
optional arg: 3
keyword arg: 4


In [253]:
all_the_args(1)

normal arg: 1
optional arg: 2
keyword arg: foo


In [254]:
all_the_args(1,3)

normal arg: 1
optional arg: 3
keyword arg: foo


In [255]:
# first class functions - functions are treated like any other 
# variable
# this function will create similar lambda function and return it
function create_adder(x)
    adder = function(y)
        return x+y
    end
    return adder
end

create_adder (generic function with 1 method)

In [256]:
func_var = create_adder(10)

#8 (generic function with 1 method)

In [257]:
func_var(3)

13

In [259]:
# stabby lambda syntax
# argument variable x -> (defining body of function) x > 2
(x -> x > 2)(3)

true

In [260]:
(x -> x < 10)(12)

false

In [261]:
# similar to create adder function above but uses the stabbly lambda 
# syntax
function create_adder(x)
    y -> x + y
end

create_adder (generic function with 1 method)

In [264]:
create_adder(10)(4)

14

In [265]:
# can also name the internal function instead of creating it via the
# lambda expression
function create_adder(x)
    function adder(y)
        x + y
    end
    adder
end

create_adder (generic function with 1 method)

In [269]:
add_10 = create_adder(10)

(::getfield(Main, Symbol("#adder#18")){Int64}) (generic function with 1 method)

In [270]:
add_10(3)

13

In [272]:
# maps the function to each element in the list and returns the 
# resulting list
map(add_10, [1,2,3])

3-element Array{Int64,1}:
 11
 12
 13

In [274]:
# returns the elements in the list that satisfy the condition
filter(x -> x > 5, [3,4,5,6,7])

2-element Array{Int64,1}:
 6
 7

In [275]:
[add_10(i) for i = [1,2,3]]

3-element Array{Int64,1}:
 11
 12
 13

In [276]:
[add_10(i) for i in [1,2,3]]

3-element Array{Int64,1}:
 11
 12
 13

In [277]:
[x for x in [3,4,5,5,6,7] if x > 5]

2-element Array{Int64,1}:
 6
 7

# Types
Type systems are traditionally two types: dynamic and static.
* dynamic: Nothing is known for defined variables until run time
* static: Program expression must have a type computable before the execution of the program
Julia is by default mostly dynamic, but does gain advantage of static type systems by allowing the user to define / indicate that certain values are of specific types.

                               Supertype
                            /            \
                          Type            Type
                          / \            /   \
                  subtype    subtype subtype subtype

## typeof
Returns the Type of the given variables
* 1 - element

In [278]:
typeof(5)

Int64

In [281]:
# DataType is the type that represents types and includes itself
typeof(Int64)

DataType

In [282]:
typeof(DataType)

DataType

In [313]:
# Users can define types (similar to records or structs in other 
# langages)
# :: operator can be used to attach type annotations to expressions 
# and variables in programs, provides extra info to the compiler and
# help confirm that the program works the way you expect
struct Tiger
    taillength::Float64
    coatcolor # not including a type annotation is the same as '::Any'
end

In [285]:
tigger = Tiger(3.5, "orange")

Tiger(3.5, "orange")

In [286]:
# The type of a struct doubles as the constructor function
# Struct-style types are called concrete types but cannot have subtypes
sherekhan = typeof(tigger)(5.6, "fire")

Tiger(5.6, "fire")

In [325]:
# Just like abstract classes in Java, Abstract types cannot be 
# instantiated but can have subtypes.
# They only serve as nodes in the type graph
abstract type Cat end

## subtypes
Returns a list of the subtypes of the given element
* 1 - element

In [292]:

# Number if an abstract type that has been pre-defined
# calling subtypes will return an array of the struct-style types that
# are subtypes
subtypes(Number)

2-element Array{Any,1}:
 Complex
 Real   

In [294]:
# cat has no subtypes defined yet, so array returns empty
subtypes(Cat)

0-element Array{Any,1}

In [296]:
subtypes(AbstractString)

4-element Array{Any,1}:
 String            
 SubString         
 SubstitutionString
 Test.GenericString

In [297]:
# every type has a super type
typeof(5)

Int64

## supertype
Returns the supertype of the given element (a single type)
* 1 - element

In [298]:
supertype(Int64)

Signed

In [299]:
supertype(Signed)# abstract types 


Integer

In [301]:
supertype(Integer)

Real

In [302]:
supertype(Number)

Any

In [303]:
supertype(supertype(Signed))

Real

In [305]:
supertype(Real)

Number

In [306]:
supertype(Number)

Any

In [308]:
# This of this as class hierarchy for types of a variable
supertype(typeof("fire"))

AbstractString

In [310]:
typeof("fire")

String

In [309]:
supertype(SubString)

AbstractString

In [312]:
subtypes(SubString)

0-element Array{Type,1}

In [317]:
# Assigning a subtype to Cat
struct Lion <: Cat
    maneColor
    roar::AbstractString
end

In [318]:
# Define more constructors for your type
# Just define a function of the same name as the type
# and call and existing constructor to get a value of the correct type
Lion(roar::AbstractString) = Lion("green", roar)

Lion

In [319]:
Lion("what")

Lion("green", "what")

In [323]:
struct Panther <: Cat # Panther is also a subtype of Cat
    eyeColor
    Panther() = new("green")
    # Panthers will only have this constructor, and no default 
    # constructor
    # Using this will give you control over how values of the type 
    # can be created, however you should try to use outer constructors
    # instead of inner constructors
end

In [324]:
Panther()

Panther("green")

# Multiple-Dispatch

In [347]:
# can specify expected type for arguments
# A generic function is composed of multiple functions implementing the
# same operation for different types
# Single dispatch occurs when the implementation is chosed based on the
# type of a single argument
function meow(animal::Lion)
    animal.roar
end

function meow(animal::Panther)
    "grrr"
end

function meow(animal::Tiger)
    "rawwr"
end

meow (generic function with 3 methods)

In [348]:
# tigger was a Tiger type
meow(tigger)

"rawwr"

In [349]:
# Panther type -> "grrr"
meow(Panther())

"grrr"

In [333]:
# Lion type -> the roar variable specified in Lion's Constructor
meow(Lion("brown", "what"))

"what"

                                Cat
                            /        \ 
                           Lion     Panther

In [335]:
# Determining the Hierarchy of Feline Species
Tiger <: Cat

false

In [336]:
Lion <: Cat

true

In [337]:
Panther <: Cat

true

In [343]:
function pet_cat(cat::Cat)
    # when you specify a function call within a string, don't have to 
    # put another '$' in front of the argument passed into it
    # Also make sure to put parentheses around the function and 
    # argument passed into it
    println("The Cat says $(meow(cat))")
end

pet_cat (generic function with 1 method)

In [344]:
pet_cat(Panther())

The Cat says grrr


In [345]:
pet_cat(Lion("green", "what"))

The Cat says what


In [346]:
try
    pet_cat(tigger)
catch e
    println(e)
end

MethodError(pet_cat, (Tiger(3.5, "orange"),), 0x000000000000622d)


In [350]:
function fight(t::Tiger, c::Cat)
    println("The $(t.coatcolor) tiger wins!")
end

fight (generic function with 1 method)

In [351]:
fight(tigger, Panther())

The orange tiger wins!


In [352]:
# redefining function
fight(l::Lion, c::Cat) = println("the victorious cat says $(meow(c))")

fight (generic function with 2 methods)

In [354]:
# Panther() is assigned to c
fight(Lion("what"), Panther())

the victorious cat says grrr


In [356]:
try
    #throws an error cause Panther() is not of type Lion
    fight(Panther(), Lion("RAWR"))
catch e
    println(e)
end

MethodError(fight, (Panther("green"), Lion("green", "RAWR")), 0x0000000000006232)


In [357]:
fight(c::Cat, l::Lion) = println("The cat beats the Lion")

fight (generic function with 3 methods)

In [366]:
try
    # throws an error because there are two functions that could be
    # called with the given arguments, since Lion is a subtype of Cat,
    # the second fight method (line 352) could be called. Since there
    # are no methods that explicitly specify Lion as being the arg, 
    # throws error cause there is more than one option
    fight(Lion("RAR"), Lion("Brown" ,"Rarr"))
catch e
    println(e)
end

the lions come to a tie


In [367]:
fight(Lion("RAR"), Lion("Brown" ,"Rarr"))

the lions come to a tie


In [368]:
fight(l::Lion, l2::Lion) = println("the lions come to a tie")

fight (generic function with 4 methods)

In [369]:
# This one is explicit because there is a method that explicitly 
# states that both arguments have to be of type Lion
fight(Lion("RAR"), Lion("Brown", "WHAT"))

the lions come to a tie


In [371]:
square_area(l) = l * l

square_area (generic function with 1 method)

In [372]:
square_area(5)

25

In [373]:
code_native(square_area, (Int32, ), syntax= :intel)

	.text
; Function square_area {
; Location: In[371]:1
; Function *; {
; Location: In[371]:1
	imul	edi, edi
;}
	mov	eax, edi
	ret
	nop	word ptr cs:[rax + rax]
;}


In [374]:
circle_area(r) = pi * r * r

circle_area (generic function with 1 method)

In [375]:
circle_area(5)

78.53981633974483